Min-Max Normalization

In [6]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Data Contoh (Ganti dengan data anda)
data= np.array([[2.0,5.0],
              [1.0,4.0],
              [3.0,6.0]])
# Inisialisasi objek MinMaxScaler
# Rumusnya = x-Xmin / Xmax-Xmin
scaler= MinMaxScaler()

# Fit and Transformasi data menggunakan Min-Max Scaling
scaled_data=scaler.fit_transform(data)

print("Data Asli: ")
print(data)

print("\nData setelah Min-Max Scaling:")
print(scaled_data)

Data Asli: 
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Min-Max Scaling:
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]


Z-Score Transformation

In [8]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Data Contoh (Ganti dengan data anda)
data= np.array([[2.0,5.0],
                [1.0,4.0],
                [3.0,6.0]])
# Inisialisasi objek StandarScaler
#Rumusnya: Z= X - mean / Standar Deviasi
scaler= StandardScaler()

# Fit and Transformasi data menggunakan Z-Score Transformation
z_score_data = scaler.fit_transform(data)

print("Data Asli: ")
print(data)

print("\nData setelah Z-Score Transformation:")
print(z_score_data)

Data Asli: 
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Z-Score Transformation:
[[ 0.          0.        ]
 [-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]]


Scaling Decimal

In [11]:
import numpy as np

#Data Contoh
data = np.array([200,300,400,500,600])

#Menentukan faktor penggeseran(scaling factor),
#misalnya 1000 untuk mengubah ke rentang 0-1

scaling_factor=1000

#Melakukan transformasi Decimal Scaling
#ini inputan rumusnya
scaled_data= data/scaling_factor

print("Data Asli: ")
print(data)

print("\n Data setelah Decimal Scaling: ")
print(scaled_data)

Data Asli: 
[200 300 400 500 600]

 Data setelah Decimal Scaling: 
[0.2 0.3 0.4 0.5 0.6]
